state_machine_rosparam_ws: /SmAtomicPerformanceTest
success_switch:
   - type: state_reached
     state_name: "sm_atomic_performance_test::State2"
failure_switch:
   - type: timeout
     duration: 10.0 # sec
