state_machine_rosparam_ws: /SmPandaMoveit2zCbInventory
success_switch:
   - type: state_reached
     state_name: "sm_panda_moveit2z_cb_inventory::State2"
failure_switch:
   - type: timeout
     duration: 10.0 # sec
